# Generated by Django 4.2.3 on 2023-08-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_liker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterUniqueTogether(
            name='liker',
            unique_together={('user', 'post_liked')},
        ),
    ]
